id: P007868
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD36435
  title: ཡུན་ནན་བོད་ཀྱི་ཤེས་རིག་ཞིབ་འཇུག་ཆེད་རྩོམ་ཕྱོགས་བསྒྲིགས། ༢
  author: ''
  volumes:
    dad8dcd73fda4909995c6b3320f7c8df:
      image_group_id: I1PD36457
      title: ''
      volume_number: 1
      total_pages: 424
ebook_metadata:
  title: ཡུན་ནན་བོད་ཀྱི་ཤེས་རིག་ཞིབ་འཇུག་ཆེད་རྩོམ་ཕྱོགས་བསྒྲིགས། ༢
  author: ''
  sku: P007868
  cover: cover.jpg
  layers:
  - pagination
