id: P007868
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:46:09.845252
source_metadata:
  id: bdr:W1PD36435
  title: ཡུན་ནན་བོད་ཀྱི་ཤེས་རིག་ཞིབ་འཇུག་ཆེད་རྩོམ་ཕྱོགས་བསྒྲིགས། ༢
  author: ''
  volumes:
    973856ee59a448d989c73ae9bad282e3:
      image_group_id: I1PD36457
      title: Volume 1 of yun nan bod kyi shes rig zhib 'jug ched rtsom phyogs bsgrigs/
        2
      volume_number: 1
      total_pages: 424
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
